### ISSUE TITLE
limited number of epochs

### ISSUE THREAD

**Issue by agni47** [itayhubara/BinaryNet#6]
Main_BinaryNet_MNIST.lua runs only for 3 epochs, regardless of the number of epochs i specify in line 32
`cmd:option('-epoch',              -1,                     'number of epochs to train, -1 for unbounded')`

everytime it achieves a test accuracy of 94-95% and stops.

**Comment by Itay-Hubara** [comment]
For some reason you have a problem plotting the convergence graph (Main_BinaryNet_MNIST.lua - line 324). Try setting opt.visualize  to 0.

Best,
Itay

**Comment by agni47** [comment]
It works after setting visualize to 0. Thanks.
